package uz.onecall.agent.core

import android.content.Context
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.util.Log
import java.io.File

object SamsungRecordingFinder {
    private const val TAG = "SamsungRecordingFinder"

    /**
     * Scan Samsung and Android native call recording folders and MediaStore
     * for high-fidelity two-way call recordings generated by Samsung native dialer.
     */
    fun findLatestNativeCallRecording(
        context: Context,
        phoneNumber: String,
        callStartTime: Long,
        callEndedTime: Long
    ): File? {
        val cleanPhone = phoneNumber.replace(Regex("[^0-9]"), "")
        val lastDigits = if (cleanPhone.length >= 7) cleanPhone.takeLast(7) else cleanPhone

        // Common Samsung Galaxy and Android call recording directories
        val directDirs = listOf(
            File(Environment.getExternalStorageDirectory(), "Recordings/Call"),
            File("/storage/emulated/0/Recordings/Call"),
            File("/storage/emulated/0/Recordings"),
            File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_RECORDINGS), "Call"),
            File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_RECORDINGS), ""),
            File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_MUSIC), "Recordings/Call")
        )

        for (dir in directDirs) {
            try {
                if (dir.exists() && dir.isDirectory) {
                    val files = dir.listFiles { file ->
                        file.isFile && (file.extension.equals("m4a", true) || 
                                        file.extension.equals("amr", true) || 
                                        file.extension.equals("mp3", true) ||
                                        file.extension.equals("wav", true))
                    } ?: emptyArray()

                    val sorted = files.sortedByDescending { it.lastModified() }
                    for (f in sorted) {
                        val modTime = f.lastModified()
                        val diffMs = Math.abs(modTime - callEndedTime)
                        val fileName = f.name
                        val matchesPhone = lastDigits.isNotBlank() && fileName.replace(Regex("[^0-9]"), "").contains(lastDigits)

                        // File modified within 90 seconds of call end OR matches the dialed/received phone number
                        if (matchesPhone || (diffMs < 90000 && modTime >= callStartTime - 10000)) {
                            Log.i(TAG, "Found Samsung native recording file: ${f.absolutePath} (${f.length()} bytes, matchesPhone=$matchesPhone, diff=${diffMs}ms)")
                            return f
                        }
                    }
                }
            } catch (e: Exception) {
                Log.w(TAG, "Could not read direct dir ${dir.absolutePath}: ${e.message}")
            }
        }

        // Search via MediaStore Audio API
        try {
            val projection = arrayOf(
                MediaStore.Audio.Media._ID,
                MediaStore.Audio.Media.DATA,
                MediaStore.Audio.Media.DISPLAY_NAME,
                MediaStore.Audio.Media.DATE_MODIFIED,
                MediaStore.Audio.Media.SIZE
            )

            val cursor = context.contentResolver.query(
                MediaStore.Audio.Media.EXTERNAL_CONTENT_URI,
                projection,
                null,
                null,
                "${MediaStore.Audio.Media.DATE_MODIFIED} DESC"
            )

            cursor?.use {
                var count = 0
                while (it.moveToNext() && count < 20) {
                    count++
                    val path = it.getString(it.getColumnIndexOrThrow(MediaStore.Audio.Media.DATA)) ?: continue
                    val name = it.getString(it.getColumnIndexOrThrow(MediaStore.Audio.Media.DISPLAY_NAME)) ?: ""
                    val modSec = it.getLong(it.getColumnIndexOrThrow(MediaStore.Audio.Media.DATE_MODIFIED))
                    val modMs = modSec * 1000
                    val size = it.getLong(it.getColumnIndexOrThrow(MediaStore.Audio.Media.SIZE))

                    if (size <= 0) continue

                    val diffMs = Math.abs(modMs - callEndedTime)
                    val matchesPhone = lastDigits.isNotBlank() && (path.contains(lastDigits) || name.contains(lastDigits))
                    val isRecordingsPath = path.contains("Recordings", ignoreCase = true) || 
                                          path.contains("Call", ignoreCase = true) ||
                                          path.contains("Voice", ignoreCase = true)

                    if (isRecordingsPath && (matchesPhone || (diffMs < 90000 && modMs >= callStartTime - 10000))) {
                        val file = File(path)
                        if (file.exists() && file.length() > 0) {
                            Log.i(TAG, "Found native recording via MediaStore: $path (${file.length()} bytes)")
                            return file
                        }
                    }
                }
            }
        } catch (e: Exception) {
            Log.w(TAG, "Error querying MediaStore: ${e.message}")
        }

        return null
    }
}
